<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign Up</name>
   <tag></tag>
   <elementGuidId>f75bed19-1a9d-4fc3-b0a7-39946f925d2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#u_4_s_Hn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='u_4_s_Hn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6bb51e19-befd-4183-a7ef-45403aba3e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>79eed601-135b-4df4-bfe2-f91aaa7e8a37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_6j mvm _6wk _6wl _58mi _3ma _6o _6v</value>
      <webElementGuid>6d14fe42-71ab-4420-a6cd-833962cda2db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>websubmit</value>
      <webElementGuid>f5099eef-0013-4aa3-90ef-14d9940f4530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>u_4_s_Hn</value>
      <webElementGuid>c583ec0c-dd3a-45d6-b23d-bff7a2f53c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign Up</value>
      <webElementGuid>9e84d62e-fe67-45bf-8d1f-f7b2e4c65e64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_4_s_Hn&quot;)</value>
      <webElementGuid>ae196323-1023-4b95-bf8a-e0d4c9836f59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='u_4_s_Hn']</value>
      <webElementGuid>2ff4e4af-749d-4d28-86ef-d1755a6ad8b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reg_form_box']/div[11]/button</value>
      <webElementGuid>f44477be-c636-4f25-8365-db99b853818a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/button</value>
      <webElementGuid>5d338c71-e473-4991-817a-a041e71d7486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'websubmit' and @id = 'u_4_s_Hn' and (text() = 'Sign Up' or . = 'Sign Up')]</value>
      <webElementGuid>afbaa5e7-8be1-4549-a06a-711d96091149</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
